env:
  contexts:
    - name: app-context
      urls:
        - http://apachea10:80
      includePaths:
        - "http://apachea10:80.*"
      authentication:
        method: form
        parameters:
          loginPageUrl: "http://apachea10:80"
          loginRequestUrl: "http://apachea10:80"
          loginRequestBody: "username={%username%}&password={%password%}"
        verification:
          method: response
          loggedInRegex: "Logout"
          loggedOutRegex: "Login"
      sessionManagement:
        method: cookie
      users:
        - name: zap-user
          credentials:
            username: root
            password: 1234

jobs:
  - type: spider
    parameters:
      context: app-context
      user: zap-user

  - type: activeScan
    parameters:
      context: app-context
      user: zap-user

  - type: report
    parameters:
      template: traditional-html
      reportDir: /zap/wrk
      reportFile: zap-report.html