ServerName localhost

# Escuchamos explícitamente en el puerto seguro
<VirtualHost *:8443>
    
    # ==========================================
    # FORZAR MOTOR SSL / TLS
    # ==========================================
    SSLEngine on
    
    # Rutas estándar donde el contenedor genera los certificados autofirmados
    SSLCertificateFile /usr/local/apache2/conf/server.crt
    SSLCertificateKeyFile /usr/local/apache2/conf/server.key

    # ==========================================
    # CONFIGURACIÓN DEL PROXY INVERSO Y FRONTEND
    # ==========================================
    ProxyPass /api http://pythona10:8080/api
    ProxyPassReverse /api http://pythona10:8080/api

    # Servir el Frontend
    DocumentRoot /var/www/html
    <Directory /var/www/html>
        DirectoryIndex index.html login.html
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    
    ErrorLog logs/error_log
    CustomLog logs/access_log combined
</VirtualHost>